vistasProyecto/routes/inversionista.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
import requests
from datetime import datetime

inversionista = Blueprint('inversionista', __name__)
URL = 'http://localhost:8090/api/inversionista'

@inversionista.route('/')
def home():
    criterios = charge_options(f'{URL}/list/criteria')   
    try:
        r = requests.get(f'{URL}/list')
        r.raise_for_status()
        data = r.json()  
        lista = data.get("data", []) 
        print("Lista enviada al template:", lista)  
        return render_template('inversionistas.html', lista=lista, opciones=criterios)
    
    except requests.exceptions.RequestException as e:
        print(f"Error al obtener la lista de inversionistas: {e}")
        return render_template('inversionistas.html', lista=[], error_message="Error inesperado al obtener los datos de la API.")

@inversionista.route('/<id>')
def inversionista_id(id):
    try:
        r = requests.get(f'{URL}/get/{id}')
        r.raise_for_status()  
        
        inversionista_data = r.json().get("data")

        if inversionista_data is None or inversionista_data == "No se encontro el inversionista con id":
            return render_template('404.html')
        
        return render_template('inversionista.html', inversionista=inversionista_data)

    except requests.RequestException as e:
        print(f"Error al obtener el inversionista: {e}")
        return render_template('404.html') 
    
@inversionista.route('/<id>/delete')
def delete_inversionista(id):
    try:
        r = requests.delete(f'{URL}/{id}/delete')
        r.raise_for_status()  
        
        if r.status_code == 200:
            return redirect(url_for('inversionista.home'))
        else:
            error_message = r.json().get('data', 'Error desconocido')
            print(f"Error al eliminar el inversionista: {error_message}")
            return redirect('/') 
    except requests.RequestException as e:
        print(f"Error al eliminar el inversionista: {e}")
        return redirect('404.html') 

@inversionista.route('/create', methods=['GET'])
def save_inversionista():
    sector = charge_options(f'{URL}/sector')
    provincia = charge_options(f'{URL}/provincia')

    inversionista = {
        "nombre": "",
        "registro": "",
        "sector": "",
        "ubicacion": ""
    }

    return render_template('forminversionistas.html', inversionista=inversionista, sector=sector, provincia=provincia, is_edit=False)

@inversionista.route('/create', methods=['POST'])
def post_inversionista_form():
    try:
        data = {
            "nombre": request.form.get('nombre'),
            "registro": request.form.get('registro'),
            "sector": request.form.get('sector'),
            "ubicacion": request.form.get('provincia')
        }

        response = requests.post(f'{URL}/save', json=data)
        response.raise_for_status()

        return redirect(url_for('inversionista.home'))

    except requests.HTTPError as e:
        if e.response.status_code == 400: 
            error_msg = e.response.json().get("error", "Error de validacion.")
            flash(f"Error al crear el inversionista: {error_msg}", "error")
        else:
            flash(f"Error inesperado al comunicarse con la API: {e}", "error")
        return redirect(url_for('inversionista.save_inversionista'))

    except Exception as e:
        flash(f"Ocurrió un error inesperado: {str(e)}", "error")
        return redirect(url_for('inversionista.save_inversionista'))
    
@inversionista.route('/<id>/edit', methods=['GET'])
def update(id):
    try:
        r = requests.get(f'{URL}/get/{id}')
        r.raise_for_status()
        response = r.json()
        
        if response.get("msg") != "OK":
            print(f"Error desde la API: {response.get('error', 'No especificado')}")
            return redirect(url_for('inversionista.home'))
        
        data = response["data"]
        
        provincia = charge_options(f'{URL}/provincia')
        sector = charge_options(f'{URL}/sector')
        
        return render_template(
            'forminversionistas.html', inversionista=data, sector=sector, provincia=provincia, is_edit=True
        )
    except requests.RequestException as e:
        print(f"Error al conectar con la API: {e}")
        return redirect(url_for('inversionista.home'))

@inversionista.route('/<id>/edit', methods=['POST'])
def update_inversionista(id):
    try:
        data = {
            "id": request.form.get('id', ''),
            "nombre": request.form.get('nombre', ''),
            "registro": request.form.get('registro', ''),
            "sector": request.form.get('sector', ''),
            "ubicacion": request.form.get('provincia', '')
        }
        response = requests.post(f'{URL}/update', json=data)
        response.raise_for_status()
        return redirect(url_for('inversionista.home'))
    except requests.RequestException as e:
        print(f"Error al crear el inversionista: {e}")
        return redirect(url_for('inversionista.update_inversionista(id)'))
    
@inversionista.route('list/sort/<attribute>/<type>/<metodo>', methods=['GET'])
def order_list(attribute, type, metodo):
    criterios = charge_options(f'{URL}/list/criteria')
    try:
        if metodo.lower() == "shell":
            if type == '1':
                type = '0' 
            elif type == '0':
                type = '1' 
        
        r = requests.get(f'{URL}/list/order/{attribute}/{type}/{metodo}')
        r.raise_for_status()
        data = r.json()
        return render_template('inversionistas.html', lista=data["data"], opciones=criterios)
    
    except requests.RequestException as e:
        print(f"Error al obtener la lista de inversionistas: {e}")
        return render_template('inversionistas.html', lista=[])

@inversionista.route('/list/search/<attribute>/<value>', methods=['GET'])
def search_criteria(attribute, value):
    criterios = charge_options(f'{URL}/list/criteria')  
    try:
        r = requests.get(f'{URL}/list/search/{attribute}/{value}')
        r.raise_for_status()
        response = r.json()  
        
        if response.get("status") == "ERROR":
            print(f"Error desde la API: {response.get('msg', 'Error desconocido')}")
            return render_template('inversionistas.html', lista=[], opciones=criterios, error=response.get('msg'))
        
        data = response.get("data", [])
        
        if not isinstance(data, list):
            data = [data]
        
        return render_template('inversionistas.html', lista=data, opciones=criterios)
    
    except requests.RequestException as e:
        print(f"Error al conectar con la API: {e}")
        return render_template('inversionistas.html', lista=[], opciones=criterios, error="Error")
    
def charge_options(endpoint):
    try:
        response = requests.get(endpoint)
        response.raise_for_status()
        data = response.json()

        opciones = []
        for item in data.get("data", []):
            nombre_formateado = format_string(item.replace("_", " "), capitalizar_palabras=True)
            opciones.append((item, nombre_formateado))

        return opciones
    except requests.RequestException as e:
        print(f"Error al obtener opciones desde {endpoint}: {e}")
        return []

def format_string(cadena, capitalizar_palabras=False):
    resultado = ''.join([' ' + char if char.isupper() and (i > 0 and not cadena[i - 1].isupper()) else char
                         for i, char in enumerate(cadena)])
    
    if capitalizar_palabras:
        return ' '.join([palabra.capitalize() for palabra in resultado.split()])
    else:
        return resultado.capitalize()

vistasProyecto/routes/participacion.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
import requests
from datetime import datetime

participacion = Blueprint('participacion', __name__)
URL = 'http://localhost:8090/api/participacion'

@participacion.route('/')
def home():
    criterios = charge_options(f'{URL}/list/criteria')
    
    try:
        r = requests.get(f'{URL}/list')
        r.raise_for_status()  
        data = r.json()
        
        return render_template('lista_participacions.html', lista=data["data"], opciones=criterios)
    
    except requests.exceptions.RequestException as e:
        print(f"Error al obtener la lista de participacions: {e}")
        return render_template('lista_participacions.html', lista=[], error_message="Error inesperado al obtener los datos de la API.")

@participacion.route('/proyecto/<id>', methods=['GET'])
def proyecto_participacion(id):
    try:
        
        r = requests.get(f'{URL}/proyecto/{id}')
        r.raise_for_status()  
        
        data = r.json().get("data")
        
        return render_template('proyecto.html', lista=data["data"])

    except requests.RequestException as e:
        print(f"Error al obtener el participacion: {e}")
        return render_template('404.html')

@participacion.route('/<id>')
def participacion_id(id):
    try:
        r = requests.get(f'{URL}/get/{id}')
        r.raise_for_status()  
        
        participacion_data = r.json().get("data")

        if participacion_data is None or participacion_data == "No se encontro el participacion con id":
            return render_template('404.html')
        
        return render_template('participacion.html', participacion=participacion_data)

    except requests.RequestException as e:
        print(f"Error al obtener el participacion: {e}")
        return render_template('404.html') 
    
@participacion.route('/<id>/delete')
def delete_participacion(id):
    try:
        r = requests.delete(f'{URL}/{id}/delete')
        r.raise_for_status()  
        
        if r.status_code == 200:
            return redirect(url_for('participacion.home'))
        else:
            error_message = r.json().get('data', 'Error desconocido')
            print(f"Error al eliminar el participacion: {error_message}")
            return redirect('/') 
    except requests.RequestException as e:
        print(f"Error al eliminar el participacion: {e}")
        return redirect('404.html') 

@participacion.route('/create', methods=['GET'])
def save_participacion():
    tipo = charge_options(f'{URL}/tipos')
    estado = charge_options(f'{URL}/estado')
    provincia = charge_options(f'{URL}/provincia')

    participacion = {
        "nombre": "",
        "descripcion": "",
        "fechaInicio": "",
        "fechaFin": "",
        "costoEstimadoInicial": "",
        "tipoEnergia": "",
        "estado": "",
        "ubicacion": "",
        "capacidad": "",
        "tiempoDeVida": ""
    }

    return render_template('formparticipacions.html', participacion=participacion, tipos=tipo, estado=estado, provincia=provincia, is_edit=False)

@participacion.route('/create', methods=['POST'])
def post_participacion_form():
    fecha_fin = request.form.get('fecha_fin', '').strip()
    try:
        fecha_inicio = datetime.strptime(request.form.get('fecha_inicio'), "%Y-%m-%d").strftime("%Y-%m-%d")
        if fecha_fin:
            try:
                fecha_fin = datetime.strptime(fecha_fin, "%Y-%m-%d").strftime("%Y-%m-%d")
            except ValueError:
                fecha_fin = None
        else:
            fecha_fin = None

        data = {
            "nombre": request.form.get('nombre'),
            "descripcion": request.form.get('descripcion'),
            "fechaInicio": fecha_inicio,
            "fechaFin": fecha_fin,
            "costoEstimadoInicial": float(request.form.get('presupuesto', 0)),
            "tipoEnergia": request.form.get('tipo'),
            "estado": request.form.get('estado'),
            "ubicacion": request.form.get('provincia'),
            "capacidad": int(request.form.get('capacidad', 0)),
            "tiempoDeVida": int(request.form.get('tiempo_de_vida', 0)),
            "inversion": float(request.form.get('inversion', 0.0)),
        }

        response = requests.post(f'{URL}/save', json=data)
        response.raise_for_status()

        return redirect(url_for('participacion.home'))

    except requests.HTTPError as e:
        if e.response.status_code == 400: 
            error_msg = e.response.json().get("error", "Error de validacion.")
            flash(f"Error al crear el participacion: {error_msg}", "error")
        else:
            flash(f"Error inesperado al comunicarse con la API: {e}", "error")
        return redirect(url_for('participacion.save_participacion'))

    except Exception as e:
        flash(f"Ocurrió un error inesperado: {str(e)}", "error")
        return redirect(url_for('participacion.save_participacion'))
    
@participacion.route('/<id>/edit', methods=['GET'])
def update(id):
    try:
        r = requests.get(f'{URL}/get/{id}')
        r.raise_for_status()
        response = r.json()
        
        if response.get("msg") != "OK":
            print(f"Error desde la API: {response.get('error', 'No especificado')}")
            return redirect(url_for('participacion.home'))
        
        data = response["data"]
        
        tipo = charge_options(f'{URL}/tipos')
        estado = charge_options(f'{URL}/estado')
        provincia = charge_options(f'{URL}/provincia')
        
        return render_template(
            'formparticipacions.html', participacion=data, tipos=tipo, estado=estado, provincia=provincia, is_edit=True
        )
    except requests.RequestException as e:
        print(f"Error al conectar con la API: {e}")
        return redirect(url_for('participacion.home'))

@participacion.route('/<id>/edit', methods=['POST'])
def update_participacion(id):
    fecha_fin = request.form.get('fecha_fin', '').strip()
    try:
        fecha_inicio = datetime.strptime(request.form.get('fecha_inicio'), "%Y-%m-%d").strftime("%Y-%m-%d")
        if fecha_fin:
            try:
                fecha_fin = datetime.strptime(fecha_fin, "%Y-%m-%d").strftime("%Y-%m-%d")
            except ValueError:
                fecha_fin = None
        else:
            fecha_fin = None
        data = {
            "id": request.form.get('id', ''),
            "nombre": request.form.get('nombre', ''),
            "descripcion": request.form.get('descripcion', ''),
            "fechaInicio": fecha_inicio if fecha_inicio else '',
            "fechaFin": fecha_fin if fecha_fin else '',
            "costoEstimadoInicial": float(request.form.get('presupuesto', 0)),
            "tipoEnergia": request.form.get('tipo', ''),
            "estado": request.form.get('estado', ''),
            "ubicacion": request.form.get('provincia', ''),
            "capacidad": int(request.form.get('capacidad', 0)),
            "tiempoDeVida": int(request.form.get('tiempo_de_vida', 0)),
            "inversion": float(request.form.get('inversion', 0.0)),
        }
        response = requests.post(f'{URL}/update', json=data)
        response.raise_for_status()
        return redirect(url_for('participacion.home'))
    except requests.RequestException as e:
        print(f"Error al crear el participacion: {e}")
        return redirect(url_for('participacion.update_participacion(id)'))
    
@participacion.route('list/sort/<attribute>/<type>/<metodo>', methods=['GET'])
def order_list(attribute, type, metodo):
    criterios = charge_options(f'{URL}/list/criteria')
    try:
        if metodo.lower() == "shell":
            if type == '1':
                type = '0' 
            elif type == '0':
                type = '1' 
        
        r = requests.get(f'{URL}/list/order/{attribute}/{type}/{metodo}')
        r.raise_for_status()
        data = r.json()
        return render_template('lista_participacions.html', lista=data["data"], opciones=criterios)
    
    except requests.RequestException as e:
        print(f"Error al obtener la lista de participacions: {e}")
        return render_template('lista_participacions.html', lista=[])

@participacion.route('/list/search/<attribute>/<value>', methods=['GET'])
def search_criteria(attribute, value):
    criterios = charge_options(f'{URL}/list/criteria')  
    try:
        r = requests.get(f'{URL}/list/search/{attribute}/{value}')
        r.raise_for_status()
        response = r.json()  
        
        if response.get("status") == "ERROR":
            print(f"Error desde la API: {response.get('msg', 'Error desconocido')}")
            return render_template('lista_participacions.html', lista=[], opciones=criterios, error=response.get('msg'))
        
        data = response.get("data", [])
        
        if not isinstance(data, list):
            data = [data]
        
        return render_template('lista_participacions.html', lista=data, opciones=criterios)
    
    except requests.RequestException as e:
        print(f"Error al conectar con la API: {e}")
        return render_template('lista_participacions.html', lista=[], opciones=criterios, error="Error")
    
def charge_options(endpoint):
    try:
        response = requests.get(endpoint)
        response.raise_for_status()
        data = response.json()

        opciones = []
        for item in data.get("data", []):
            nombre_formateado = format_string(item.replace("_", " "), capitalizar_palabras=True)
            opciones.append((item, nombre_formateado))

        return opciones
    except requests.RequestException as e:
        print(f"Error al obtener opciones desde {endpoint}: {e}")
        return []

def format_string(cadena, capitalizar_palabras=False):
    resultado = ''.join([' ' + char if char.isupper() and (i > 0 and not cadena[i - 1].isupper()) else char
                         for i, char in enumerate(cadena)])
    
    if capitalizar_palabras:

vistasProyecto/templates/forminversionistas.html
{% extends "base.html" %}
{% block title %}{{ 'Editar Proyecto' if is_edit else 'Agregar Nuevo Proyecto' }}{% endblock %}
{% block content %}
<div class="container py-5">
    <h2 class="mb-4">{{ 'Editar Proyecto' if is_edit else 'Agregar Nuevo Proyecto' }}</h2>
    <div class="card shadow-sm p-4">
        <!-- Acción del formulario depende si es edición o creación -->
        <form method="POST" action="{{ url_for('inversionista.update_inversionista', id=inversionista.id) if is_edit else url_for('inversionista.post_inversionista_form') }}">
            <div class="row">
                {% if is_edit %}
                <!-- Si es edición, pasamos el id -->
                <input type="hidden" name="id" value="{{ inversionista.id }}">
                {% endif %}
                <div class="form-group col-md-6">
                    <label for="nombre">Nombre:</label>
                    <input type="text" id="nombre" name="nombre" class="form-control" value="{{ inversionista.nombre if is_edit else '' }}" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="registro">Registro:</label>
                    <input type="text" id="registro" name="registro" class="form-control" value="{{ inversionista.registro if is_edit else '' }}" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="sector">Sector:</label>
                    <select id="sector" name="sector" class="form-control" required>
                        {% for key, value in sector %}
                            <option value="{{ key }}" {% if is_edit and inversionista.sector == key %}selected{% endif %}>{{ value }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label for="provincia">Ubicación:</label>
                    <select id="provincia" name="provincia" class="form-control" required>
                        {% for key, value in provincia %}
                            <option value="{{ key }}" {% if is_edit and inversionista.ubicacion == key %}selected{% endif %}>{{ value }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="text-center mt-4">
                <button type="submit" class="btn btn-primary w-50">
                    {{ 'Actualizar Proyecto' if is_edit else 'Guardar Proyecto' }}
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

vistasProyecto/templates/inversionistas.html
{% extends "base.html" %}

{% block title %}Lista de Invesionistas{% endblock %}

{% block content %}
<script>
    $(document).ready(function () {
        function url_change() {
            var url = "http://localhost:5000/inversionista/list/search";
            var search = $("#search").val();
            var criterio = $("#criterio").val();
            var new_url = url + "/" + criterio + "/" + search;
            $("#btn").attr("href", new_url);
        }
    
        $("#search").keyup(function () {
            url_change();
        });
        $("#criterio").change(function () {
            url_change();
        });
    
        function updateArrowUrls() {
            var method = $("#order_c").val(); 
        
            $("a.text-primary").each(function () {
                var baseUrl = $(this).data("original-href"); 
                $(this).attr("href", baseUrl + method);
            });
        }
        
        $("a.text-primary").each(function () {
            if (!$(this).data("original-href")) {
                $(this).data("original-href", $(this).attr("href")); 
            }
        });
        
        $("#order_c").change(function () {
            updateArrowUrls();
        });
        
        updateArrowUrls();
        });
</script>


<div class="content-container py-4 px-3">
    <div class="container-fluid bg-white shadow-sm rounded py-4">
        <h2 class="text-primary mb-4">Invesionistas</h2>
        <div class="d-flex align-items-center mb-4">
            <a href="{{ url_for('inversionista.save_inversionista') }}" class="btn btn-outline-primary">
                <i class="fas fa-plus-circle"></i> Agregar Invesionista
            </a>
        </div>
    </div>

    <div class="content-section py-4 px-3">
        <div class="container-fluid bg-white shadow-sm rounded py-4">
            <div class="d-flex justify-content-between mb-4">
                <div class="d-flex flex-wrap gap-3 mb-4">
                    <div class="d-flex align-items-center">
                        <label for="criterio" class="mr-2">Criterio:</label>
                        <select id="criterio" class="form-select w-auto mr-2">
                            {% for key, value in opciones %}
                                <option value="{{ key }}" {% if key == selected_key %}selected{% endif %}>
                                    {{ value }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <div class="d-flex align-items-center mr-2">
                        <input type="text" id="search" class="form-control" placeholder="Buscar Invesionista">
                    </div>
                    
                    <div class="d-flex align-items-center">
                        <a id="btn" class="btn btn-primary">
                            <i class="fas fa-search"></i>
                        </a>
                    </div>
                </div>
                
                <div class="d-flex align-items-center gap-2">
                    <label for="order_c" class="mr-2">Elige un metodo</label>
                    <select id="order_c" class="form-select w-auto">
                        <option value="shell">Shell</option>
                        <option value="merge">Merge</option>
                        <option value="quick">Quick</option>
                    </select>
                </div>
            </div>

            <h3 class="text-secondary mb-4">Lista de Invesionistas</h3>
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-project-diagram"></i> Nombre
                                </div>
                                <div>
                                    <a href="{{ url_for('inversionista.order_list', attribute='nombre', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-up"></i>
                                    </a>
                                    <a href="{{ url_for('inversionista.order_list', attribute='nombre', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-down"></i>
                                    </a>
                                </div>
                            </th>
                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-file-signature"></i> Registro
                                </div>
                                <div>
                                    <a href="{{ url_for('inversionista.order_list', attribute='registro', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-up"></i>
                                    </a>
                                    <a href="{{ url_for('inversionista.order_list', attribute='registro', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-down"></i>
                                    </a>
                                </div>
                            </th>
                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-map"></i> Ubicación
                                </div>
                                <div>
                                    <a href="{{ url_for('inversionista.order_list', attribute='ubicacion', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-up"></i>
                                    </a>
                                    <a href="{{ url_for('inversionista.order_list', attribute='ubicacion', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-down"></i>
                                    </a>
                                </div>
                            </th>
                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-industry"></i> Sector
                                </div>
                                <div>
                                    <a href="{{ url_for('inversionista.order_list', attribute='sector', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-up"></i>
                                    </a>
                                    <a href="{{ url_for('inversionista.order_list', attribute='sector', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-caret-down"></i>
                                    </a>
                                </div>
                            </th>
                            <th class="text-center" style="max-width: 150px; font-size: 0.9em;">
                                Acciones
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if lista %}
                            {% for item in lista %}
                                <tr class="text-center">
                                    <td>
                                        <a href="{{ url_for('inversionista.inversionista_id', id=item.id) }}" 
                                           class="btn btn-outline-primary btn-sm w-100 text-start opacity-50 hover-opacity-100" 
                                           style="transition: opacity 0.3s ease;">
                                            {{ item.nombre }}
                                        </a>
                                    </td>
                                    <td>{{ item.registro }}</td>
                                    <td>{{ item.sector }}</td>
                                    <td>{{ item.ubicacion }}</td>
                                    <td>
                                        <div class="d-flex">
                                            <a href="{{ url_for('inversionista.update', id=item.id) }}" class="btn btn-primary text-white p-3 mx-2 rounded d-flex justify-content-center align-items-center shadow-lg">
                                                <i class="fas fa-edit fa-lg"></i>
                                            </a>
                                            <a href="{{ url_for('inversionista.delete_inversionista', id=item.id) }}" class="btn btn-danger text-white p-3 mx-2 rounded d-flex justify-content-center align-items-center shadow-lg">
                                                <i class="fas fa-trash-alt fa-lg"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="5" class="text-center">No hay datos disponibles.</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

{% endblock %}